using System.Collections;
using System.Collections.Generic;
using FinderMod.Inputs;
using FinderMod.Inputs.LizardCosmetics;
using FinderMod.Search.Util;
using Unity.Burst;
using static FinderMod.Search.Util.LizardUtil;

namespace FinderMod.Search.Options.LizardCosmetics
{
    /// <summary>
    /// Base option for lizard cosmetics. Useful to extend for modded lizards that do not change the default cosmetics code or add their own afterwards.
    /// </summary>
    public abstract class BaseLizardCosmetics : Option
    {
        /// <summary>
        /// The type of the lizard.
        /// </summary>
        protected LizardType type;
        /// <summary>
        /// A container for any <see cref="Subholder"/>s used by the input
        /// </summary>
        protected CosmeticsItemContainer cosmetics;
        /// <summary>
        /// Whether or not to return a <see cref="Melanistic"/> in <see cref="GetResults(XORShift128, RotType)"/>
        /// </summary>
        protected bool returnMelanistic = false;

        /// <summary>
        /// Contains the <see cref="LizardRotCosmetic"/> instance for referencing during distance calculations.
        /// </summary>
        protected LizardRotCosmetic lizardRotCosmetic = null!;
        private readonly EnumInput<RotType> rotTypeInput = null!;

        /// <summary>
        /// The <see cref="CreatureTemplate.Type"/> of the represented lizard. Overrideable in the event of a modded lizard.
        /// </summary>
        public override CreatureTemplate.Type? RepresentedCreature
        {
            get => overrideCreature ?? LizardUtil.LizardTypeToTemplateType(type);
            protected set => overrideCreature = value;
        }
        private CreatureTemplate.Type? overrideCreature = null;

        /// <summary>
        /// Initializes with a <see cref="CosmeticsItemContainer"/> containing a <see cref="LizardRotSubholder"/> if Watcher is enabled.
        /// </summary>
        /// <param name="type">Lizard type</param>
        public BaseLizardCosmetics(LizardType type)
        {
            this.type = type;
            elements = [cosmetics = new CosmeticsItemContainer()];
            if (ModManager.Watcher)
            {
                var submodule = new LizardRotSubholder(lizardRotCosmetic = new LizardRotCosmetic());
                rotTypeInput = submodule.RotTypeInput;
                cosmetics.Add(submodule);
            }
        }

        /// <summary>
        /// Runs <see cref="GetResults(XORShift128, RotType)"/> with the rot type specified by <see cref="rotTypeInput"/>
        /// </summary>
        /// <param name="Random">An instance of <see cref="XORShift128"/> initialized to the seed of the lizard</param>
        /// <returns>All lizard cosmetics generated by the lizard</returns>
        /// <seealso cref="GetResults(XORShift128, RotType)"/>
        protected IEnumerable GetResults(XORShift128 Random)
        {
            return GetResults(Random, ModManager.Watcher ? rotTypeInput.value : RotType.None);
        }

        /// <summary>
        /// Returns all lizard cosmetics generated by the lizard.
        /// </summary>
        /// <param name="Random">An instance of <see cref="XORShift128"/> initialized to the seed of the lizard</param>
        /// <param name="rotType">The rot stage of the lizard</param>
        /// <returns>All lizard cosmetics generated by the lizard assuming an unmodified call to <see cref="Lizard(AbstractCreature, World)"/></returns>
        [BurstCompile]
        protected IEnumerable GetResults(XORShift128 Random, RotType rotType)
        {
            // Lizard rot!
            var (x, y, z, w) = (Random.x, Random.y, Random.z, Random.w);

            switch (type)
            {
                case LizardType.Pink
                or LizardType.Green
                or LizardType.Blue
                or LizardType.Yellow
                or LizardType.Salamander
                or LizardType.Red
                or LizardType.Caramel
                or LizardType.Blizzard
                or LizardType.Basilisk
                or LizardType.Indigo:
                    Random.Shift(4);
                    break;
                case LizardType.Cyan:
                    Random.Shift(5);
                    break;
                default: break;
            }

            var rotModule = new LizardRotModule(Random, rotType);

            Random.InitState(x, y, z, w);

            // Calculate IVars ahead of time
            Random.Shift(5);
            float tailLength = ClampedRandomVariation(0.5f, 0.2f, 0.3f, Random) * 2f;
            Random.Shift(2);
            float tailColor = 0f;
            if (type != LizardType.White && Random.Value > 0.5f)
            {
                tailColor = Random.Value;
            }
            if (type == LizardType.Black) Random.Shift(2);

            // Extra offsetting
            Random.Shift(
                (type == LizardType.Caramel ? 6 : 4)
                + NumTailSegments(type)
                + NumTongueSegments(type)
                + 1 // head
                );

            bool blackSalamander = Random.Value < 0.33333334f; // melanistic salamander chance (yes it gets called even if not a salamander)
            if (type == LizardType.Salamander)
            {
                yield return new Melanistic(blackSalamander);
            }

            // Cosmetics! (finally)
            TailTuftVars.TailTuftGraphicCalculation? tailTuftGraphic = null;
            if (type == LizardType.Eel)
            {
                yield return new AxolotlGillsVars(0, Random, ref tailTuftGraphic);

                yield return new TailGeckoScalesVars(0, Random, tailColor, null);
                if (Random.Value < 0.75f)
                {
                    yield return new LongShoulderScalesVars(0, Random, tailLength, type, ref tailTuftGraphic);
                    yield return new TailFinVars(0, Random, tailLength, type);
                }
                else
                {
                    yield return new ShortBodyScalesVars(0, Random, tailLength, type);
                    if (Random.Value < 0.75f)
                    {
                        yield return new TailFinVars(1, Random, tailLength, type);
                    }
                    else
                    {
                        yield return new TailTuftVars(0, Random, tailLength, type, ref tailTuftGraphic);
                    }
                }
            }
            else if (type == LizardType.Zoop)
            {
                if (Random.Value < 0.175f)
                {
                    yield return new WingScalesVars(0, Random);
                }
                else
                {
                    yield return new SpineSpikesVars(0, Random, tailLength, type, ref tailTuftGraphic);
                }
                yield return new TailTuftVars(1, Random, tailLength, type, ref tailTuftGraphic);
            }

            if (type == LizardType.Cyan)
            {
                WingScalesVars? wingScalesVars = null;
                if (Random.Value < 0.75f)
                {
                    yield return wingScalesVars = new WingScalesVars(1, Random);
                }
                if (Random.Value < 0.5f && tailColor == 0f)
                {
                    yield return new TailTuftVars(2, Random, tailLength, type, ref tailTuftGraphic);
                }
                else
                {
                    yield return new TailGeckoScalesVars(1, Random, tailColor, wingScalesVars);
                }
                yield return new JumpRingsVars(0);
            }
            else if (type == LizardType.White)
            {
                if (Random.Value < 0.4f)
                {
                    yield return new BumpHawkVars(0, Random, tailLength, type);
                }
                else if (Random.Value < 0.4f)
                {
                    yield return new ShortBodyScalesVars(1, Random, tailLength, type);
                }
                else if (Random.Value < 0.2f)
                {
                    yield return new LongShoulderScalesVars(1, Random, tailLength, type, ref tailTuftGraphic);
                }
                else if (Random.Value < 0.2f)
                {
                    yield return new LongHeadScalesVars(0, Random, type, ref tailTuftGraphic);
                }
                if (Random.Value < 0.5f)
                {
                    yield return new TailTuftVars(3, Random, tailLength, type, ref tailTuftGraphic);
                }
            }
            else
            {
                int backDecals = 0;
                bool longShoulderScales = false;
                bool shortBodyScales = false;

                if (type == LizardType.Indigo)
                {
                    yield return new SkinkStripesVars(0);
                    yield return new SkinkSpecklesVars(0, Random);
                }
                else if (type == LizardType.Caramel && Random.Value < 0.6f)
                {
                    yield return new BodyStripesVars(0, Random, tailLength, type);
                    backDecals++;
                }
                else if (Random.Value < 0.06666667f || (Random.Value < 0.8f && type == LizardType.Green) || (Random.Value < 0.7f && type == LizardType.Black))
                {
                    yield return new SpineSpikesVars(1, Random, tailLength, type, ref tailTuftGraphic);
                    backDecals++;
                }
                else if (Random.Value < 0.033333335f && type != LizardType.Caramel)
                {
                    yield return new BumpHawkVars(1, Random, tailLength, type);
                    backDecals++;
                }
                else if ((Random.Value < 0.04761905f || (type == LizardType.Pink && Random.Value < 0.5f) || (type == LizardType.Red && Random.Value < 0.9f)) && type != LizardType.Salamander)
                {
                    yield return new LongShoulderScalesVars(2, Random, tailLength, type, ref tailTuftGraphic);
                    longShoulderScales = true;
                    backDecals++;
                }
                else if ((Random.Value < 0.0625f || (type == LizardType.Blue && Random.Value < 0.5f)) && type != LizardType.Salamander)
                {
                    yield return new ShortBodyScalesVars(2, Random, tailLength, type);
                    shortBodyScales = true;
                    backDecals++;
                }
                else if (type == LizardType.Green && Random.Value < 0.5f)
                {
                    yield return new ShortBodyScalesVars(3, Random, tailLength, type);
                    shortBodyScales = true;
                    backDecals++;
                }

                if (type != LizardType.Salamander && type != LizardType.Indigo)
                {
                    if (type == LizardType.Caramel && Random.Value < 0.5f)
                    {
                        yield return new TailTuftVars(4, Random, tailLength, type, ref tailTuftGraphic);
                    }
                    else if (Random.Value < 0.11111111f || (backDecals == 0 && Random.Value < 0.7f) || (type == LizardType.Pink && Random.Value < 0.6f)  || (type == LizardType.Blue && Random.Value < 0.96f))
                    {
                        yield return new TailTuftVars(5, Random, tailLength, type, ref tailTuftGraphic);
                    }
                    else if (backDecals < 2 && type == LizardType.Green && Random.Value < 0.7f)
                    {
                        if (Random.Value < 0.5f || longShoulderScales || shortBodyScales)
                        {
                            yield return new TailTuftVars(6, Random, tailLength, type, ref tailTuftGraphic);
                        }
                        else
                        {
                            yield return new LongShoulderScalesVars(3, Random, tailLength, type, ref tailTuftGraphic);
                            longShoulderScales = true;
                            backDecals++;
                        }
                    }
                }

                if (Random.Value < (backDecals == 0 ? 0.7f : 0.1f) && type != LizardType.Salamander && type != LizardType.Yellow && type != LizardType.Indigo && (!longShoulderScales && Random.Value < 0.9f || Random.Value < 0.033333335f))
                {
                    yield return new LongHeadScalesVars(1, Random, type, ref tailTuftGraphic);
                }

                if (type == LizardType.Salamander)
                {
                    yield return new AxolotlGillsVars(1, Random, ref tailTuftGraphic);
                    yield return new TailFinVars(2, Random, tailLength, type);
                }
                else if (type == LizardType.Black)
                {
                    yield return new WhiskersVars(0, Random);
                }
                else if (type == LizardType.Yellow)
                {
                    yield return new AntennaeVars(0, Random);
                    if (backDecals == 0 && Random.Value < 0.6f)
                    {
                        yield return new ShortBodyScalesVars(4, Random, tailLength, type);
                        backDecals++;
                    }
                }
                else if (type == LizardType.Red || type == LizardType.Train)
                {
                    yield return new LongShoulderScalesVars(4, Random, tailLength, type, ref tailTuftGraphic);
                    yield return new SpineSpikesVars(2, Random, tailLength, type, ref tailTuftGraphic);
                    backDecals += 2;
                    if (Random.Value < 0.5f)
                    {
                        yield return new TailFinVars(3, Random, tailLength, type);
                    }
                    else
                    {
                        yield return new TailTuftVars(7, Random, tailLength, type, ref tailTuftGraphic);
                    }
                }
                else if (type == LizardType.Basilisk)
                {
                    yield return new BumpHawkVars(2, Random, tailLength, type);
                    yield return new TailGeckoScalesVars(2, Random, tailColor, null);
                    yield return new TailGeckoScalesVars(3, Random, tailColor, null);
                    for (int i = 0; i < 9; i++)
                    {
                        yield return new ShortBodyScalesVars(5, Random, tailLength, type);
                        yield return new TailTuftVars(8, Random, tailLength, type, ref tailTuftGraphic);
                    }
                    yield return new LongHeadScalesVars(2, Random, type, ref tailTuftGraphic);
                    // BasiliskSlowField
                    yield return new SkinkSpecklesVars(1, Random);
                }
                else if (type == LizardType.Blizzard)
                {
                    for (int i = 0; i < 5; i++)
                    {
                        if ((double)Random.Value + 1E-05 < 0.5)
                        {
                            yield return new AxolotlGillsVars(2, Random, ref tailTuftGraphic);
                        }
                    }
                    for (int i = 0; i < 5; i++)
                    {
                        if ((double)Random.Value + 1E-05 < 0.5)
                        {
                            yield return new AxolotlGillsVars(3, Random, ref tailTuftGraphic);
                        }
                    }
                    yield return new LongHeadScalesVars(3, Random, type, ref tailTuftGraphic);
                    for (int i = 0; i < 8; i++)
                    {
                        if ((double)Random.Value + 1E-05 < 0.5)
                        {
                            yield return new ShortBodyScalesVars(6, Random, tailLength, type);
                        }
                    }
                    for (int i = 0; i < 5; i++)
                    {
                        if ((double)Random.Value + 1E-05 < 0.800000011920929)
                        {
                            yield return new SpineSpikesVars(3, Random, tailLength, type, ref tailTuftGraphic);
                        }
                    }
                    for (int i = 0; i < 10; i++)
                    {
                        yield return new TailTuftVars(9, Random, tailLength, type, ref tailTuftGraphic);
                    }
                    if ((double)Random.Value + 1E-05 < 0.05000000074505806)
                    {
                        yield return new WhiskersVars(1, Random);
                    }
                    // BlizzardBeam
                    // BlizzardSteam
                }
                else if (type == LizardType.Peach)
                {
                    yield return new PeachHeadStripesVars(0, Random);
                    yield return new TailFinVars(4, Random, tailLength, type);
                    yield return new PeachBackFinVars(0, Random);
                }

                if (backDecals == 0 && type == LizardType.Caramel)
                {
                    yield return new BumpHawkVars(3, Random, tailLength, type);
                    // backDecals++;
                }
            }

            if (type == LizardType.Zoop)
            {
                yield return new SnowAccumulationVars(0, Random);
            }

            if (rotType != RotType.None)
            {
                yield return new LizardRotVars(Random, rotModule, rotType);
            }
        }

        /// <summary>
        /// Returns strings to display in the Values tab for a particular id.
        /// </summary>
        /// <param name="Random"></param>
        /// <returns>A string representation for the cosmetics of an id</returns>
        protected override IEnumerable<string> GetValues(XORShift128 Random)
        {
            var (x, y, z, w) = (Random.x, Random.y, Random.z, Random.w);

            foreach (var value in GetResults(Random, RotType.None))
            {
                if (value is ILizardCosmeticVars vars)
                {
                    foreach (var text in vars.GetValues())
                    {
                        yield return text;
                    }
                }
            }

            if (ModManager.Watcher)
            {
                yield return null!;
                RotType[] rotTypes = [RotType.Slight, RotType.Opossom, RotType.Full];
                foreach (var rotType in rotTypes)
                {
                    Random.InitState(x, y, z, w);
                    foreach (var result in GetResults(Random, rotType))
                    {
                        if (result is LizardRotVars rotVars)
                        {
                            foreach (var value in rotVars.GetValues())
                            {
                                yield return value;
                            }
                        }
                    }
                }
            }
        }
    }
}
