#pragma kernel CS_IDFinderMain

#include "IDFinder.cginc"
#include "Personality.cginc"


float Execute(uint4 random, StructuredBuffer<Input> inputs)
{
    Personality p = InitPersonality(random);

    float d = 0;
    d += Distance(p.aggression, inputs[0]);
    d += Distance(p.bravery, inputs[1]);
    d += Distance(p.dominance, inputs[2]);
    d += Distance(p.energy, inputs[3]);
    d += Distance(p.nervous, inputs[4]);
    d += Distance(p.sympathy, inputs[5]);
    
    return d;
}
